// tests/e2e/shareImport.spec.ts — S06 chromium share-token add-flow smoke.
//
// Owns the visual + interaction verification for the Share/Import screen. The
// pure preview/collision/import logic is exercised by
// `tests/unit/ui/share/model.test.ts` at the node layer; this spec proves the
// composed screen mounts and the ADD path writes to `repo` when no collision
// exists.
//
// Chromium-only, following the S03 boot smoke's precedent — the cross-engine
// determinism specs need Chromium + Firefox + WebKit; a functional UI smoke
// running on all three would double e2e wall-clock for zero signal.
//
// NOT-HERMETIC NOTE (from the SESSION-06 orchestration envelope): S04 and S05
// e2e specs share this webServer. A sibling failure is a `surprises` note,
// not a fix — this spec only asserts its own testids.

import { expect, test } from '@playwright/test';

test.skip(({ browserName }) => browserName !== 'chromium', 'UI smoke: chromium only');

const APP_URL = 'http://localhost:8081/starship-skirmish/';

// Pre-authored share token for a fig-wasp fighter named "The Argument".
// Generated by encodeShareToken(catalog, buildFighter('The Argument'))
// against the current v1 catalog. See tests/unit/io/codec/shareToken.test.ts
// for the encoder's contract — the token round-trips deterministically.
const KNOWN_TOKEN = 'UwEBAgMNHgAMVGhlIEFyZ3VtZW50AQ';

// Known benign browser console messages (S03 precedent). A regression in
// share/screen code produces console errors NOT matching these patterns.
const KNOWN_BENIGN_CONSOLE_MESSAGES: readonly RegExp[] = [
  /frame-ancestors.*ignored.*<meta>/i,
  /Failed to load resource.*404.*(Not Found)?/i,
];
const isBenign = (t: string): boolean =>
  KNOWN_BENIGN_CONSOLE_MESSAGES.some((r) => r.test(t));

test.describe('share/import screen — token preview + add flow', () => {
  test('#/share?t=<valid> mounts the preview panel', async ({ page, context }) => {
    // Clear the persisted library so this run starts with an empty encyclopedia
    // and the ADD path is a direct-insert (no collision modal).
    await context.clearCookies();
    await context.addInitScript(() => {
      try {
        for (const k of Object.keys(window.localStorage)) {
          if (k.startsWith('starship-skirmish:')) window.localStorage.removeItem(k);
        }
      } catch {
        // ignore — non-localStorage backing stores are rare in test env
      }
    });

    const consoleErrors: string[] = [];
    page.on('console', (msg) => {
      if (msg.type() !== 'error') return;
      const text = msg.text();
      if (isBenign(text)) return;
      consoleErrors.push(text);
    });

    await page.goto(`${APP_URL}#/share?t=${encodeURIComponent(KNOWN_TOKEN)}`);
    await expect(page.getByTestId('screen-share')).toBeVisible();
    await expect(page.getByTestId('share-preview')).toBeVisible();
    await expect(page.getByTestId('share-preview-name')).toHaveText('The Argument');
    await expect(page.getByTestId('share-preview-chassis')).toContainText('FIGHTER');
    await expect(page.getByTestId('share-preview-points')).toHaveText('11');
    // ADD button is present and enabled.
    await expect(page.getByTestId('share-add-btn')).toBeEnabled();

    expect(
      consoleErrors,
      `console errors: ${consoleErrors.join(' | ')}`,
    ).toEqual([]);
  });

  test('clicking ADD writes the build and navigates to the encyclopedia', async ({
    page,
    context,
  }) => {
    // Fresh library so we get a direct-insert (no collision modal).
    await context.addInitScript(() => {
      try {
        for (const k of Object.keys(window.localStorage)) {
          if (k.startsWith('starship-skirmish:')) window.localStorage.removeItem(k);
        }
      } catch {
        // ignore
      }
    });
    await page.goto(`${APP_URL}#/share?t=${encodeURIComponent(KNOWN_TOKEN)}`);
    await expect(page.getByTestId('share-add-btn')).toBeVisible();
    await page.getByTestId('share-add-btn').click();
    // Post-add: URL hash flips to encyclopedia, and localStorage carries one
    // build. Screen might be an S04-in-flight surface — we assert only what
    // this session owns.
    await expect
      .poll(() => page.evaluate(() => window.location.hash))
      .toBe('#/encyclopedia');
    const buildCount = await page.evaluate(() => {
      let count = 0;
      for (const k of Object.keys(window.localStorage)) {
        if (k.startsWith('starship-skirmish:build:')) count += 1;
      }
      return count;
    });
    expect(buildCount).toBe(1);
  });

  test('#/share (no token) renders the empty paste field', async ({ page }) => {
    await page.goto(`${APP_URL}#/share`);
    await expect(page.getByTestId('screen-share')).toBeVisible();
    await expect(page.getByTestId('share-token-input')).toBeVisible();
    // No preview until a token arrives.
    await expect(page.getByTestId('share-preview')).toHaveCount(0);
  });
});
